import = ["~/.config/alacritty/rose-pine.toml"]

[env]
TERM = "xterm-256color"

[font]
normal.family = "JetBrainsMono Nerd Font"
# size = 14
size = 18

[cursor]
style.blinking = "On"

[window]
  startup_mode = "Maximized"
  padding = { x = 4, y = 1 }
  opacity = 0.99
